/**
 * JS Tag v3.4.5 (Wed Jun 03 15:52:17 UTC 2020)
 * RevJet
 * https://www.revjet.com/
 */
(function(){var h,k="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},l;if("function"==typeof Object.setPrototypeOf)l=Object.setPrototypeOf;else{var m;a:{var n={X:!0},p={};try{p.__proto__=n;m=p.X;break a}catch(a){}m=!1}l=m?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var q=l;var r=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){return!!("srcdoc"in document.createElement("iframe"))});var t="undefined"!==typeof window.postMessage,aa="undefined"!==typeof window.JSON&&"function"===typeof window.JSON.parse,ba="undefined"!==typeof window?window:{};function v(a){a=a.split(".");for(var b=ba,c;c=a.shift();)if(null!=b[c])b=b[c];else return null;return b};var ca=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"==typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},da=Array.prototype.reduce?function(a,b,c){return Array.prototype.reduce.call(a,b,c)}:function(a,b,c){var d=c;ca(a,function(c,f){d=b.call(void 0,d,c,f,a)});return d},ea=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"==typeof a?
a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};function fa(a,b){a:{var c=a.length;for(var d="string"==typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break a}c=-1}return 0>c?null:"string"==typeof a?a.charAt(c):a[c]};function w(a,b,c){if("string"==typeof b)a.style[b]=c;else for(var d in b)a.style[d]=b[d]};function x(a){try{window.document.write(a)}catch(b){}}function y(a,b,c){c=void 0===c?window.document:c;a=c.createElement(a);for(var d in b.s)b.s.hasOwnProperty(d)&&a.setAttribute(d,b.s[d]);for(var e in b.style)b.style.hasOwnProperty(e)&&(a.style[e]=b.style[e]);return a}function z(a){var b={margin:0,padding:0,position:"relative",left:0,top:0,opacity:1,visibility:"visible",overflow:"hidden",border:"none",cssFloat:"none"};if(a)for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b}
function A(a){var b={allowtransparency:"false",frameborder:"0",hspace:"0",marginwidth:"0",marginheight:"0",scrolling:"no",vspace:"0"};if(a)for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b};function B(a,b,c){"undefined"!==typeof window.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c)}function C(a,b,c){"undefined"!==typeof window.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent("on"+b,c)};function ha(a){return a.replace(/<script[^>]*/ig,function(a){return a.replace(/(\s+)(type)(\s*=\s*)/ig,"$1data-revjet-script-type$3").replace(/(\s+)(language)(\s*=\s*)/ig,"$1data-revjet-script-language$3").replace(/(\s+)(src)(\s*=\s*)/ig,"$1data-revjet-script-src$3")+' type="text/revjet"'})}function ia(a,b){var c=b.bind(this);a.addEventListener?a.addEventListener("load",c,!1):a.onreadystatechange=function(){if("loaded"===a.readyState||"complete"===a.readyState)a.onreadystatechange=null,c()}}
function D(a,b,c,d){return function(){if(0===b.length)d&&d();else{var e=b.shift(),f=D(a,b,c,d);if("SCRIPT"===e.nodeName&&"text/revjet"===e.type){var g=c.createElement("script");g.async=!1;var u=e.getAttribute("data-revjet-script-type");u&&(g.type=u);g.id=e.id;g.text=e.text||e.textContent||e.innerHTML||"";(u=e.getAttribute("data-revjet-script-language"))&&g.setAttribute("language",u);e.charset&&(g.charset=e.charset);if(e=e.getAttribute("data-revjet-script-src"))g.src=e;g.src&&ia(g,f);a.insertBefore(g,
null);g.src||f()}else if(e.innerHTML&&0<=e.innerHTML.toLowerCase().indexOf("<script")){for(g=[];e.firstChild;)g.push(e.removeChild(e.firstChild));a.insertBefore(e,null);D(e,g,c,f)()}else a.insertBefore(e,null),f()}}}function ja(a,b,c){if(b){var d=c.createElement("div");d.innerHTML="L<div>"+ha(b)+"</div>";b=[];for(d=d.lastChild;d.firstChild;)b.push(d.removeChild(d.firstChild));d=b}else d=[];D(a,d,c)()};var E=null;function ka(){this.c=v("extern")||v("$sf.ext");this.a=!1;this.f=[]}function la(a,b,c){if(a.c&&!a.a)try{$sf.ext.register(b,c,function(b,c){for(var d=a.f,e=0;e<d.length;e++)d[e](b,c)}),a.a=!0}catch(d){}};function F(a,b){this.j=a;this.a={};this.c=this.f=null;this.i=[];this.m=[];this.g=[];if(b&&b.c&&!this.f){var c=this.j.document.getElementById("REVJET_Tag-MESSAGING_FRAME");c?this.f=c:(this.f=y("iframe",{s:A({id:"REVJET_Tag-MESSAGING_FRAME"}),style:z({display:"none"})}),this.j.document.body.appendChild(this.f))}}function ma(a,b){return ea(a.i,function(a){return a.R===b})}function G(a,b,c){var d=fa(a.i,function(a){return a.R===b});d?c(d.ga):a.g=a.g.concat({$:b,code:c})}
F.prototype.o=function(a,b,c){if(a.initialized){for(b=this.m.length-1;0<=b;b--){var d=this.m[b];d.target===c&&(d.target.postMessage(JSON.stringify(d.message),"*"),this.m.splice(b,1))}if(!ma(this,c))for(this.i=this.i.concat({R:c,ga:a}),b=this.g.length-1;0<=b;b--)d=this.g[b],d.$===c&&d.code(a)}};
function na(a,b){a.c||(a.c=function(c){if(c&&"data"in c){var d=null;try{d=JSON.parse(c.data)}catch(f){}if(d&&"module"in d&&d.method&&"REVJET_Tag.Ad"===d.module){var e=b[d.method];e&&e.call(a,d.properties,d.messageId,c.source)}}},B(a.f?a.f.contentWindow:a.j,"message",a.c))}function H(a){a.c&&(C(a.j,"message",a.c),a.c=null)};var I=0;
function J(a,b,c){c=void 0===c?!1:c;var d=a.getSlotResponseObject();this.W=!!window.inDapIF;this.c=a;var e=window.parent;if(this.W&&window!==e){var f=this.c.getSlotObjectName();e[f]?I=++e[f].instanceNumber:(e[f]={},e[f].instanceNumber=++I)}else I++;this.T=b;this.S=d.content||"";this.O=d.failover_query_string;this.P=d.failover_url;this.o=a.getAdWidth();this.u=a.getAdHeight();this.g=0;this.m=window;E||(E=new ka);this.K=E;la(this.K,this.o,this.u);if(this.f=c?null:new F(this.m,this.K))this.f.a.close=this.aa.bind(this),
this.f.a.collapse=this.ba.bind(this),this.f.a.expand=this.ca.bind(this),this.f.a.relayAction=this.ea.bind(this),this.f.a.reload=this.fa.bind(this),this.f.a.refresh=this.da.bind(this)}h=J.prototype;h.aa=function(a,b,c){this.H(c)&&this.c.destroy()};h.ca=function(){};h.ba=function(){};h.ea=function(){};h.fa=function(a,b,c){this.H(c)&&this.c.reload()};h.da=function(a,b,c){this.H(c)&&this.c.refresh()};h.H=function(){return!1};h.Z=function(){return this.T};
function K(a){var b=a.O;if(a.P||b){b=a.P;var c=a.O;if(b){c=a.c;var d=c.getAdapter();b="https://"+c.getAdsDomainName()+(d?"/"+d:"")+b}else b=c?(-1!==c.toString().indexOf("msgCode=1005")?L(a,"/~cdn/Ads/ad_shared/static/406.html"):L(a,"/~cdn/Ads/ad_shared/static/failover.html"))+"?"+c:null;if(b)return'<!DOCTYPE html>\n<html>\n<head>\n<style type="text/css">* {padding:0;margin:0;}</style>\n</head>\n<body style="background-color: #fff;">\n<iframe '+['src="'+b+'"','allowtransparency="false" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"',
'width="'+a.o+'"','height="'+a.u+'"','style="border:0;vertical-align:bottom;width:'+a.o+"px;height:"+a.u+'px;"'].join(" ")+"></iframe>\n</body>\n</html>"}return a.S}h.I=function(){var a=this.g;if((0===a||2===a)&&this.f){var b=this.f;t&&aa&&(b.a.setElementsInitialized=b.o.bind(b),na(b,b.a))}0===a&&window.context&&window.context.reportRenderedEntityIdentifier&&window.context.reportRenderedEntityIdentifier(oa(this))};h.G=function(){1===this.g&&this.f&&H(this.f)};
h.F=function(){if(3!==this.g){if(this.f){var a=this.f;H(a);a.m=[];a.g=[];a.i=[]}this.K.f=[]}};h.L=function(){return[]};h.Y=function(){return 3===this.g};function L(a,b){var c=a.c,d=c.getAdapter();return"https://"+c.getCdnDomainName()+(d?"/"+d:"")+b}function oa(a){if(a=K(a)){var b=/<title>([0-9]+)\/[0-9]+<\/title>/gi.exec(a);return b&&0<b.length?"revjet-"+b[1]:"revjet-S"+a.length}return"revjet-S0"}function M(a){a=a.c;return(a.getOptions?a.getOptions():{}).content?!1:r()}
function N(a){a=a.c;var b=a.getOptions?a.getOptions():{};a={};for(var c in b)b.hasOwnProperty(c)&&"content"!==c&&"b64"!==c&&(a[c]=b[c]);c="{}";try{c=JSON.stringify(a)}catch(d){}return c}J.prototype.adDestroyed=J.prototype.Y;J.prototype.getFrames=J.prototype.L;J.prototype.destroyAd=J.prototype.F;J.prototype.hideAd=J.prototype.G;J.prototype.showAd=J.prototype.I;J.prototype.getAdType=J.prototype.Z;var pa=/<\/body>\s*<\/html>/i;function O(a,b,c){J.call(this,a,b,c);a=a.getSlotResponseObject();this.N=a.embd_tag_id;this.V=a.disable_iframe;this.U=a.deliveryWrapper;this.J=!!a.autoscale;this.A=!!a.autohide;this.D=this.j=this.i=this.a=null;this.M=!!a.close_button;this.B=this.C=this.v=null}O.prototype=k(J.prototype);O.prototype.constructor=O;
if(q)q(O,J);else for(var P in J)if("prototype"!=P)if(Object.defineProperties){var Q=Object.getOwnPropertyDescriptor(J,P);Q&&Object.defineProperty(O,P,Q)}else O[P]=J[P];O.a=J.prototype;function R(a,b){try{var c=a.contentDocument||a.contentWindow.document;c.open();c.write(b);c.close()}catch(d){}}function S(a,b){var c=a.o;c=0>=b?1:b/c;return{scale:c.toFixed(4),height:Math.round(a.u*c)}}
function T(a,b){if(b){var c=a.i;if(c)return c.getBoundingClientRect().width}else{var d=U(a);if(d)return c=a.m.document.createElement("div"),c.style.cssText="position:relative;left:0;top:0;right:auto;bottom:auto;width:100%;border:none;padding:0;margin:0;visibility:hidden;",d.appendChild(c),d=c.getBoundingClientRect().width,c.parentNode.removeChild(c),d}return 0}
function qa(a){function b(){var b=T(a,!0);b=S(a,b);var c=a.i;c&&w(c,"height",b.height+"px");(c=a.j)&&w(c,"height",b.height+"px");if(c=a.a)b="scale("+b.scale+")",c.style.webkitTransform=b,c.style.transform=b}var c=a.m;c.requestAnimationFrame?c.requestAnimationFrame(function(){return b()}):c.setTimeout(function(){return b()},16)}function V(a){a=A({width:a.o,height:a.u,name:"revjet-single-iframe","data-revjet-options":N(a)});return y("iframe",{s:a,style:z()})}
function ra(a){a=A({name:"revjet-single-iframe","data-revjet-options":N(a)});return y("iframe",{s:a,style:{display:"block",position:"absolute",top:"0",bottom:"0",left:"0",width:"100%",height:"100%",border:"0",padding:"0",margin:"0"}})}
function sa(a){if(!/loaded|complete/.test(window.document.readyState)){var b=a.c,c=K(a);a.V||!pa.test(c)?x(c):(x('<ins id="'+b.getHolderId()+'"></ins>'),a.m.setTimeout(function(){var d=a.m.document.getElementById(b.getHolderId());a.j=d;var e=z({width:a.o+"px",height:a.u+"px"});w(d,e);a.A&&(W(d,{width:e.width,height:e.height,position:e.position,visibility:e.visibility}),w(d,{width:"1px",height:"1px",position:"absolute",visibility:"hidden"}));e=V(a);a.a=e;var f=M(a);f&&e.setAttribute("srcdoc",c);d.appendChild(e);
f||R(e,c);f=a.f;a.A&&f&&G(f,e.contentWindow,function(a){a&&a.isEmptyPersonalization||X(d)})},0))}}function ta(a,b){a.A&&w(b,{width:"1px",height:"1px",visibility:"hidden"});var c=ra(a);a.a=c;var d=K(a),e=M(a);e&&c.setAttribute("srcdoc",d);b.appendChild(c);e||R(c,d);d=a.f;a.A&&d&&G(d,c.contentWindow,function(a){a&&a.isEmptyPersonalization||w(b,{width:"100%",height:"100%",visibility:"inherit"})});Y(a)}
function Y(a){a.M&&a.v&&(a.C=ua(a),B(a.v,"click",a.C));a.J&&(a.B=function(){return qa(a)},B(a.m,"resize",a.B))}function Z(a){a.J&&a.B&&(C(a.m,"resize",a.B),a.B=null);a.C&&a.v&&(C(a.v,"click",a.C),a.C=null)}h=O.prototype;h.H=function(a){var b=this.a;return!(!b||b.contentWindow!==a)};
h.I=function(){var a=this;J.prototype.I.call(this);if(2===this.g){var b=this.i,c=U(this);this.c.isResponsive()&&w(c,"display","block");b&&w(b,"display","inline-block");Y(this);this.g=1}else if(0===this.g){b=this.c;var d=this.m.document;if(b.getIsSyncLoading())sa(this),this.g=1;else{c=this.N;if(this.c.isResponsive()&&c){var e=document.getElementById(c);if(e){var f={position:"absolute",display:"block",width:"100%",height:"100%",padding:"0",margin:"0",overflow:"hidden"};0===c.indexOf("revjet-tag")?w(e,
f):this.D||(this.D=y("div",{s:{},style:f}),e.appendChild(this.D))}}if(c=U(this)){if(this.c.isResponsive())ta(this,c);else if("div"===this.U)ja(c,K(this),d);else{var g={display:"inline-block",width:this.o+"px",height:this.u+"px"};e=1;if(d=this.J)e=T(this,!1),f=S(this,e),e=f.scale,g={display:"block",width:"100%",height:f.height+"px"};f=z(g);this.i=y("ins",{s:{id:b.getWrapperId()},style:f});g=z(g);g.display="block";this.j=y("ins",{s:{id:b.getHolderId()},style:g});this.A&&(W(this.i,{width:f.width,height:f.height,
position:f.position,visibility:f.visibility}),w(this.i,{width:"1px",height:"1px",position:"absolute",visibility:"hidden"}),W(this.j,{width:g.width,height:g.height,position:g.position,visibility:g.visibility}),w(this.j,{width:"1px",height:"1px",position:"absolute",visibility:"hidden"}));this.a=V(this);M(this)&&this.a.setAttribute("srcdoc",K(this));d&&(b="scale("+e+")",this.a.style.webkitTransformOrigin="0 0",this.a.style.transformOrigin="0 0",this.a.style.webkitTransform=b,this.a.style.transform=b,
this.a.style.backfaceVisibility="hidden");this.j.appendChild(this.a);this.M&&!this.v&&(this.v=b=va(this),this.j.appendChild(b));for(this.i.appendChild(this.j);c.firstChild;)c.removeChild(c.firstChild);c.appendChild(this.i);M(this)||R(this.a,K(this));b=this.f;this.A&&b&&G(b,this.a.contentWindow,function(b){b&&b.isEmptyPersonalization||(X(a.i),X(a.j))});Y(this)}this.g=1}}}};
function va(a){var b=L(a,"/~cdn/JS/03/3.4.5/x-button.28x28.png");var c=void 0===c?window.document:c;b=y("img",{s:{src:b},style:{margin:0,padding:0,position:"absolute",left:"auto",bottom:"auto",right:0,top:0,border:0,zIndex:999999,width:"18px",height:"18px",cursor:"pointer",overflow:"hidden",cssFloat:"none",webkitAppearance:"none"}},c);w(b,{zIndex:989999,left:a.o-18+"px",right:"auto",pointerEvents:"auto"});return b}function ua(a){return function(){a.c.hide()}}
function U(a){var b=a.c,c=a.m.document;b=a.N||b.getContainerId();return a.D||c.getElementById(b)}h.G=function(){J.prototype.G.call(this);if(1===this.g){Z(this);if(this.c.isResponsive()){var a=U(this);w(a,"display","none")}else this.i&&w(this.i,"display","none");this.g=2}};
h.F=function(){J.prototype.F.call(this);if(3!==this.g){Z(this);if(this.c.isResponsive()){var a=U(this);a&&a&&a.parentNode&&a.parentNode.removeChild(a)}else this.a&&(a=this.a)&&a.parentNode&&a.parentNode.removeChild(a);this.v=this.i=this.j=this.a=null;this.g=3}};h.L=function(){return this.a?[this.a]:[]};function W(a,b){for(var c in b)b.hasOwnProperty(c)&&a.setAttribute("data-revjet-"+c,b[c])}
function X(a){w(a,da(["width","height","position","visibility"],function(b,c){var d=a.getAttribute("data-revjet-"+c);null!=d&&(b[c]=d);return b},{}))}O.prototype.getFrames=O.prototype.L;O.prototype.destroyAd=O.prototype.F;O.prototype.hideAd=O.prototype.G;O.prototype.showAd=O.prototype.I;REVJET_Tag.ModuleManager.getInstance().setLoaded("banner",O);})();

