var hl_styles = new String("<CENTER><B>To choose an alternative Fossies highlight(ing) style you can use the <A HREF=\"/select_hl_style_lang\">style selection page</A> or just quickly select one of the styles below</B></CENTER><HR>" +
"<TABLE><TR>" +
"<TD><A HREF=\'?m=h&s=standard\'>standard</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=acid\'>acid</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=aiseered\'>aiseered</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=andes\'>andes</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=anotherdark\'>anotherdark</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=autumn\'>autumn</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=baycomb\'>baycomb</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=bclear\'>bclear</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=biogoo\'>biogoo</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=bipolar\'>bipolar</A>&nbsp;</TD>" +
"</TR><TR><TD><A HREF=\'?m=h&s=blacknblue\'>blacknblue</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=bluegreen\'>bluegreen</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=breeze\'>breeze</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=bright\'>bright</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=camo\'>camo</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=candy\'>candy</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=clarity\'>clarity</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=dante\'>dante</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=darkblue\'>darkblue</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=darkbone\'>darkbone</A>&nbsp;</TD>" +
"</TR><TR><TD><A HREF=\'?m=h&s=darkness\'>darkness</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=darkslategray\'>darkslategray</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=darkspectrum\'>darkspectrum</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=denim\'>denim</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=dusk\'>dusk</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=earendel\'>earendel</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=easter\'>easter</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=edit-anjuta\'>edit-anjuta</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=edit-bbedit\'>edit-bbedit</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=edit-eclipse\'>edit-eclipse</A>&nbsp;</TD>" +
"</TR><TR><TD><A HREF=\'?m=h&s=edit-emacs\'>edit-emacs</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=edit-flashdevelop\'>edit-flashdevelop</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=edit-gedit\'>edit-gedit</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=edit-jedit\'>edit-jedit</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=edit-kwrite\'>edit-kwrite</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=edit-matlab\'>edit-matlab</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=edit-msvs2008\'>edit-msvs2008</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=edit-nedit\'>edit-nedit</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=edit-purebasic\'>edit-purebasic</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=edit-vim-dark\'>edit-vim-dark</A>&nbsp;</TD>" +
"</TR><TR><TD><A HREF=\'?m=h&s=edit-vim\'>edit-vim</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=edit-xcode\'>edit-xcode</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=ekvoli\'>ekvoli</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=fine_blue\'>fine_blue</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=freya\'>freya</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=fruit\'>fruit</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=golden\'>golden</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=greenlcd\'>greenlcd</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=kellys\'>kellys</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=leo\'>leo</A>&nbsp;</TD>" +
"</TR><TR><TD><A HREF=\'?m=h&s=lucretia\'>lucretia</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=manxome\'>manxome</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=maroloccio\'>maroloccio</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=matrix\'>matrix</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=moe\'>moe</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=molokai\'>molokai</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=moria\'>moria</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=navajo-night\'>navajo-night</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=navy\'>navy</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=neon\'>neon</A>&nbsp;</TD>" +
"</TR><TR><TD><A HREF=\'?m=h&s=nightshimmer\'>nightshimmer</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=night\'>night</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=nuvola\'>nuvola</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=olive\'>olive</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=orion\'>orion</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=oxygenated\'>oxygenated</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=pablo\'>pablo</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=peaksea\'>peaksea</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=print\'>print</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=rand01\'>rand01</A>&nbsp;</TD>" +
"</TR><TR><TD><A HREF=\'?m=h&s=rdark\'>rdark</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=relaxedgreen\'>relaxedgreen</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=rootwater\'>rootwater</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=seashell\'>seashell</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=solarized-dark\'>solarized-dark</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=solarized-light\'>solarized-light</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=tabula\'>tabula</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=tcsoft\'>tcsoft</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=the\'>the</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=vampire\'>vampire</A>&nbsp;</TD>" +
"</TR><TR><TD><A HREF=\'?m=h&s=whitengrey\'>whitengrey</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=xoria256\'>xoria256</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=zellner\'>zellner</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=zenburn\'>zenburn</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=zmrok\'>zmrok</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=github\'>(github)</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=sourceforge\'>(sourceforge)</A>&nbsp;</TD>" +
"<TD><A HREF=\'?m=h&s=bold\'>(bold)</A>&nbsp;</TD>" +
"</TR></TABLE>")
var hl_dl_tip = new String("By the way: A member file download can also be achieved by clicking within a package contents listing on the according byte size field.")
